# Generated by Django 2.2.14 on 2020-07-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_auto_20200701_0839"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="hjgfjhgjhg",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="kjhjkhkhk",
            field=models.TextField(blank=True, null=True),
        ),
    ]
